### PR TITLE
Added cross-realm support

### PR DESCRIPTION
**Pull request by stevenvachon**

### CODE REVIEW

**Comment by stevenvachon** [comment]
@TehShrike ^^

**Comment by stevenvachon** [comment]
@TehShrike is it good to merge, then, or are we waiting on something? I'd like to use this in a public package ASAP

**Comment by TehShrike** [comment]
Whoops, I don't have publish rights to this package on npm.

@yoshuawuyts can you run `npm publish`?  I already bumped the version in the package.json.

**Comment by yoshuawuyts** [comment]
@TehShrike add you as a maintainer (:

**Comment by TehShrike** [comment]
Published as 1.1.0.

**Pull request merged**
